version: '3'

services:
  app:
    image: gruz0/crawler-web
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: '${USER_ID}'
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    stdin_open: true
    tty: true
    volumes:
      - ./data:/app/data
      - ./public/uploads:/app/public/uploads
    ports:
      - 127.0.0.1:3001:3000
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'curl http://localhost:3000/api/status | grep true > /dev/null',
        ]
      interval: 5s
      timeout: 5s

  db:
    image: postgres:12-alpine
    env_file: .env
    volumes:
      - .data:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $POSTGRES_USER -d $POSTGRES_DB']
      interval: 5s
      timeout: 5s
