name: Docker Image CI

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: hadolint/hadolint-action@v1.5.0
      with:
        dockerfile: Dockerfile

    - name: Build the Docker image
      run: make build-docker-image
