name: Lint

on:
  push:
    branches:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest

    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://app:password@localhost/app_test
      TZ: Europe/Moscow
      PGTZ: UTC

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 17

      - run: npm ci
      - run: make lint
