name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://app:password@localhost/app_test
      TZ: Europe/Moscow
      PGTZ: UTC

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 17
          cache: npm

      - run: npm ci
      - run: make lint
